---
title: "13 Regression Discontinuity Design (RDD)"
summary: "..."
author: Andrew Christopher Herman
date: 2025-12-03
publishdate: 2025-07-11
slides: example

bibliography: "./../../../Stats_II.bib"
csl: "./../../../assets/american-sociological-review.csl"
---

Regression discontinuity designs (RDD) are a valuable tool for estimating causal effects when a treatment is assigned based on a clear threshold or cutoff. Imagine a scholarship program awarded to all students scoring above a certain mark on an exam. RD designs exploit this sharp cutoff to compare outcomes for students just above and just below the threshold, assuming those students are otherwise very similar. This approach mimics a randomized experiment near the cutoff point.

For instance, we could use an RD design to study the effect of that scholarship on future academic performance. By comparing students who barely qualified for the scholarship with those who just missed out, we can isolate the effect of the scholarship, assuming those students are virtually identical in other aspects.

However, RD designs have limitations. The estimated causal effect only applies to individuals near the threshold. Additionally, the validity of RD designs hinges on the assumption that individuals cannot manipulate their assignment around the cutoff. If students could easily cheat on the exam to secure the scholarship, the design's validity would be compromised.

Therefore, it's crucial to carefully assess the suitability of RD designs and address potential concerns about manipulation or other violations of the underlying assumptions before drawing causal conclusions.

Lecture slides: [**Lecture 13**](/Lectures/13-RegDD/13-RegDD.html)..

## Readings

**@angrist_mastering_2014[Ch. 4 Regression discontinuity Designs]**.

## References
