---
title: "Exercise 1 (20 minutes)"
subtitle: "When you're done, assist some of the others ..."
output: webexercises::webexercises_default
---

```{r setup, include = FALSE}
options(htmltools.dir.version = FALSE, servr.interval = 0.5, width = 115, digits = 2)
knitr::opts_chunk$set(
  collapse = TRUE, message = FALSE, 
  warning = FALSE, cache = FALSE,
  comment = "#", strip.white = TRUE)

library(webexercises)
library(essentials)
```

1. Let's take another look at our research question on the legacy of colonialism. Use the same setup as in lecture 4 to answer the following question: To which degree do differences in the number of years since independence from colonialism explain why we saw significant differences between countries colonized by different colonial powers?

2. Let's take another look at education and political efficacy. Use the same setup as in lecture 4 to answer the following question: Is immigrant origin confounding (i.e. introducing selection bias) into the association between education and political efficacy? Define immigrant origin as a factor variable with three levels: "Mainsteam" (born in DK and both parents born in DK), "Immigrant" (born abroad), "Descendant of immigrant (at least one parent born abroad). First discuss whether immigrant origin is a confounding variable or not.
